apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: 
spec:
  # Secret names are always required.
  secretName: tls-cert
  dnsNames:
    - dev.cloudwithankit.in
  issuerRef:
    name: letsencrypt-ci
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer